# -*- coding: utf-8 -*-
"""XML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zNY6hrd4H8pBzfeMbcdNWWeA4fQE1-OB
"""

!pip install dict2xml==1.6.1

from dict2xml import dict2xml
from dict2xml import dict2xml as d2x
data = {
    'PARTS' : {
        'PART mode="auto': {
            'KIND_OF_PART': 'MaPSA',
            'NAME_LABEL': 'AEM_35494_016L',
            'LOCATION': 'AEMtec',
            'VERSION': '2.0'
        }
    }
  }
print (d2x(data, wrap="all", indent="  "))

with open('35494_016_PSP_MANL.txt') as file:
  myfile = file.read()
  print(myfile)

data1 = myfile.split('\n\n')
data2 = data1[1]
data3 = data2.split(';')
data4 = data3[4].split('-')

#fname = input('Enter file name: ')
fname='35494_016_PSP_MANL.txt'
with open(fname) as file:
  myfile = file.read()
  #print(myfile)

#print(fname)
fname_split = fname.split('_')